module.exports = {
  Query: {
    forecast: (_, { city }, { dataSources }) => dataSources.weatherApi.getWeatherByCity({ city }),
  },
  CONDITIONS: {
    THUNDERSTORM: 'Thunderstorm',
    DRIZZLE: 'Drizzle',
    RAIN: 'Rain',
    SNOW: 'Snow',
    CLOUDS: 'Clouds',
    CLEAR: 'Clear',
    MIST: 'Mist',
    SMOKE: 'Smoke',
    HAZE: 'Haze',
    DUST: 'Dust',
    FOG: 'Fog',
    SAND: 'Sand',
    ASH: 'Ash',
    SQUALL: 'Squall',
    TORNADO: 'Tornado',
  },
  // CONDITIONS: {
  //   THUNDERSTORM: 'Thunderstorm',
  //   DRIZZLE: 'Drizzle',
  //   RAIN: 'Rain',
  //   SNOW: 'Snow',
  //   CLOUDS: 'Clouds',
  //   CLEAR: 'Clear',
  // },
  // ATMOSPHERE: {
  //   MIST: 'Mist',
  //   SMOKE: 'Smoke',
  //   HAZE: 'Haze',
  //   DUST: 'Dust',
  //   FOG: 'Fog',
  //   SAND: 'Sand',
  //   ASH: 'Ash',
  //   SQUALL: 'Squall',
  //   TORNADO: 'Tornado',
  // },
};
